[theme]

# Primary accent for interactive elements
primaryColor = '#48BF84'

# Background color for the main content area
backgroundColor = '#061826'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#317272'

# Color used for almost all text
textColor = '#F4F4F6'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"